version: '3.8'

services:
  statistic-app:
    build: ./
    command: ./wait-for-postgres.sh db ./statistic
    env_file:
      - ./.env.dev
    ports:
      - 8081:8081
    depends_on:
      - db
#    environment:
#      - DB_PASSWORD=statistic

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: statistic
      POSTGRES_USER: statistic
    expose:
      - "5432" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5436:5432"
    command: -p 5432
  migrate-up:
    image: migrate/migrate
    volumes:
    - ./schema:/migrations
    command: "-path=/migrations -database postgres://statistic:statistic@db:5432/statistic?sslmode=disable up"
    depends_on:
      - db